spring:
  application:
     name: shengwu
  datasource:
     #url: 'jdbc:mysql://47.104.7.73:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false'
     url: 'jdbc:mysql://47.93.216.109:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false'
     username: yiyao
     password: rrheD2P6zHDSCYdA
     driver-class: 'com.mysql.jdbc.Driver'
     database-name: yiyao
     init-sql: mysql/init.sql
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
  data:
     elasticsearch:
       cluster-name: docker-cluster
       cluster-nodes: 39.96.82.217:9300
       #cluster-nodes: 45.77.86.209:9300
       #cluster-nodes: 47.104.7.73:9300

server:
  port: 8080
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
files:
  path: /root/files

es:
  #endpoint: 45.77.86.209:9200
  endpoint: 39.96.82.217:9200
